name: benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - feature/*

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: g++-11
            architecture: -m64
            sourcefile: unique_scattered_lookup.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            reportdir: gcc-m64
            os: ubuntu-20.04
            install: g++-11
            command: sudo cset shield --exec -- nice -n -20 sudo -u gha ./benchmark
          - compiler: clang++-12
            architecture: -m64
            sourcefile: unique_scattered_lookup.cpp
            compileroptions: -std=c++2a -O3 -DNDEBUG -DHAVE_ABSEIL
            outputfile: benchmark
            reportdir: clang-m64
            os: ubuntu-20.04
            command: sudo cset shield --exec -- nice -n -20 sudo -u gha ./benchmark
                        
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        if: matrix.install
        run: |
          # sudo -E apt-add-repository -y ppa:ubuntu-toolchain-r/test
          if uname -p | grep -q 'x86_64'; then sudo dpkg --add-architecture i386 ; fi
          sudo apt-get update
          sudo apt-get install -y ${{matrix.install}}
      - name: Install Boost
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/boostorg/boost.git boost-root
          cd boost-root
          git checkout boost-1.80.0.beta1
          git submodule update --init
          ./bootstrap.sh
          ./b2 -d0 headers
      - name: Install Abseil
        run: |
          cd $GITHUB_WORKSPACE
          git clone -b lts_2022_06_23 https://github.com/abseil/abseil-cpp.git abseil-root
      - name: Install fastrange
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/lemire/fastrange.git fastrange-root
      - name: Install fxa_unordered
        run: |
          cd $GITHUB_WORKSPACE
          git clone -b feature/foa_rc https://github.com/joaquintides/fxa_unordered fxa_unordered-root
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE
          ${{matrix.compiler}} --version
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.architecture}} ${{matrix.compileroptions}} -o ${{matrix.outputfile}} -I$GITHUB_WORKSPACE/boost-root -I$GITHUB_WORKSPACE/abseil-root -I$GITHUB_WORKSPACE/fastrange-root -I$GITHUB_WORKSPACE/fxa_unordered-root
      - name: Set reportfile name
        run: |
          echo "REPORT_FILE=${{matrix.reportdir}}/${{matrix.sourcefile}}.csv" >> $GITHUB_ENV
      - name: Run benchmarks
        run: |
          echo "running benchmarks and saving to "${REPORT_FILE}
          ./${{matrix.outputfile}} | tee ${REPORT_FILE}
      - name: Push benchmark results to repo
        run: |
          git config --global user.name 'joaquintides'
          git config --global user.email 'joaquintides@users.noreply.github.com'
          git add ${REPORT_FILE}
          git stash -- ${REPORT_FILE}
          git pull
          git stash pop
          git add ${REPORT_FILE}
          git commit -m "updated benchmark results"
          git push
